export default [
  {
    id: 1,
    alcoholVolume: 40,
    capacity: 750,
    kind: "블랜디드 위스키",
    manufacturer: "디아지오",
    name: "조니워커 블루 레이블",
  },
  {
    id: 2,
    alcoholVolume: 40,
    capacity: 700,
    kind: "스카치 위스키",
    manufacturer: "시바스 브라더스",
    name: "로얄살루트 21년 시그니처 블랜디드",
  },
  {
    id: 3,
    alcoholVolume: 40,
    capacity: 700,
    kind: "꼬냑",
    manufacturer: "LVMH",
    name: "헤네시 V.S.O.P",
  },
  {
    id: 4,
    alcoholVolume: 40,
    capacity: 700,
    kind: "싱글몰트 위스키",
    manufacturer: "하이랜드 디스틸러",
    name: "맥캘란 12년산 싱글몰트 위스키",
  },
  {
    id: 5,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "마틴 밀러 진",
  },
  {
    id: 6,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "지바인 누아종",
  },
  {
    id: 7,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "쓰리소사이어티스 정원 진",
  },
  {
    id: 8,
    alcoholVolume: null,
    capacity: 750,
    kind: null,
    manufacturer: null,
    name: "진 마레",
  },
  {
    id: 9,
    alcoholVolume: null,
    capacity: 500,
    kind: null,
    manufacturer: null,
    name: "몽키 47",
  },
  {
    id: 10,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "봄베이 브램블",
  },
  {
    id: 11,
    alcoholVolume: null,
    capacity: 750,
    kind: null,
    manufacturer: null,
    name: "봄베이 사파이어",
  },
  {
    id: 12,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "그린올즈 와일드 베리 핑크 진",
  },
  {
    id: 13,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "핸드릭스 진",
  },
  {
    id: 14,
    alcoholVolume: null,
    capacity: 1000,
    kind: null,
    manufacturer: null,
    name: "플랜테이션 오리지날 다크 럼",
  },
  {
    id: 15,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "플랜테이션 파인애플 럼",
  },
  {
    id: 16,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "세일러 제리",
  },
  {
    id: 17,
    alcoholVolume: null,
    capacity: 750,
    kind: null,
    manufacturer: null,
    name: "애플톤 시그니쳐 블렌드",
  },
  {
    id: 18,
    alcoholVolume: null,
    capacity: 750,
    kind: null,
    manufacturer: null,
    name: "하바나 클럽 3 아뇨스",
  },
  {
    id: 19,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "펄라 델 노르테 아네호",
  },
  {
    id: 20,
    alcoholVolume: null,
    capacity: 750,
    kind: null,
    manufacturer: null,
    name: "고든스 진",
  },
  {
    id: 21,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "탱커레이 No. 10",
  },
  {
    id: 22,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "비피터",
  },
  {
    id: 23,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "비피터 24",
  },
  {
    id: 24,
    alcoholVolume: null,
    capacity: 3000,
    kind: null,
    manufacturer: null,
    name: "크리스탈 헤드 보드카",
  },
  {
    id: 25,
    alcoholVolume: null,
    capacity: 1750,
    kind: null,
    manufacturer: null,
    name: "크리스탈 헤드 보드카",
  },
  {
    id: 26,
    alcoholVolume: null,
    capacity: 750,
    kind: null,
    manufacturer: null,
    name: "단즈카 애플",
  },
  {
    id: 27,
    alcoholVolume: null,
    capacity: 750,
    kind: null,
    manufacturer: null,
    name: "단즈카 크랜라즈",
  },
  {
    id: 28,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "쿠바이 10년",
  },
  {
    id: 29,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "디플로마티코 레제르바 익스클루시바",
  },
  {
    id: 30,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "디플로마티코 만투아노",
  },
  {
    id: 31,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "딕타도르 12년",
  },
  {
    id: 32,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "콰이페",
  },
  {
    id: 33,
    alcoholVolume: null,
    capacity: 750,
    kind: null,
    manufacturer: null,
    name: "그레이구스 보드카",
  },
  {
    id: 34,
    alcoholVolume: null,
    capacity: 750,
    kind: null,
    manufacturer: null,
    name: "그레이구스 라 포아",
  },
  {
    id: 35,
    alcoholVolume: null,
    capacity: 750,
    kind: null,
    manufacturer: null,
    name: "그레이구스 스트론",
  },
  {
    id: 36,
    alcoholVolume: null,
    capacity: 750,
    kind: null,
    manufacturer: null,
    name: "그레이구스 오렌지",
  },
  {
    id: 37,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "말리부 라임",
  },
  {
    id: 38,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "말리부",
  },
  {
    id: 39,
    alcoholVolume: null,
    capacity: 750,
    kind: null,
    manufacturer: null,
    name: "바카디 오로",
  },
  {
    id: 40,
    alcoholVolume: null,
    capacity: 750,
    kind: null,
    manufacturer: null,
    name: "바카디 카르타 블랑카",
  },
  {
    id: 41,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "바카디 모히토",
  },
  {
    id: 42,
    alcoholVolume: null,
    capacity: 750,
    kind: null,
    manufacturer: null,
    name: "릴렛",
  },
  {
    id: 43,
    alcoholVolume: null,
    capacity: 750,
    kind: null,
    manufacturer: null,
    name: "베어허그 크랜베리",
  },
  {
    id: 44,
    alcoholVolume: null,
    capacity: 750,
    kind: null,
    manufacturer: null,
    name: "베어허그 망고",
  },
  {
    id: 45,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "그랑 마니에르 코르동 루즈",
  },
  {
    id: 46,
    alcoholVolume: null,
    capacity: 700,
    kind: null,
    manufacturer: null,
    name: "코인트로",
  },
];
